// Code généré automatiquement. Ne pas modifier.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
.......ff............
....ffff2ff..........
..ffeeeef2ff.........
.ffeeeeef22ff........
.feeeeffeeeef........
.fffffee2222ef.......
fffe222ffffe2f.......
ffffffffeeefff.......
fefe444b144eef.......
.fee444bf44ef........
..feee44444e..ff9....
...f444444fffffffffff
...f444444444fffffff.
...fffffff4444.......
..ffffffff...........
..fff..ff............
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Code généré automatiquement. Ne pas modifier.
